version: "3.8"

services:
  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:80"
    depends_on:
      - server
